Stats/complex/views.py
from flask import Blueprint, render_template, send_file, request, jsonify

from Stats.complex.graphs import create_bell_graph
from Stats.complex.utils import Calculator, Distribution

complex_ = Blueprint("complex", __name__)

functions = ["normal", "binomial", "f-distribution", "t-distribution", "chi-squared-distribution",
             "poisson-distribution", "geometric-distribution"]
accuracy = 4  # default accuracy value
calculator = Calculator(accuracy)


@complex_.route("/complex", methods=["GET", "POST"])
def home():
	"""
	The main calculator page
	:return: a template
	"""
	return render_template("complex_home.html", functions=functions)


@complex_.get("/complex/normal")
def normal():
	"""
	The normal distribution page
	:return: a template
	"""

	distribution = Distribution("Normal Distribution", "Continuous Probability Distribution",
	                            "The Normal distribution, also known as the Gaussian distribution, is a "
	                            "probability distribution that is symmetric about the mean, showing that data near "
	                            "the mean are more frequent in occurrence than data far from the mean.In graphical "
	                            "form, the normal distribution appears as a 'bell curve'.")
	# Source: https://www.investopedia.com/terms/n/normaldistribution.asp#:~:text=Normal%20distribution%2C%20also%20known%20as,as%20a%20%22bell%20curve%22.
	# probability = calculator.normal(mean, standard_deviation, x)
	return render_template("normal.html",
	                       distribution=distribution, functions=functions)


@complex_.post("/complex/normal")
def normal_calculation():
	try:
		data = request.json
		mean = data.get("mean", 0)
		sd = data.get("sd", 0)
		x = data.get("x", 0)

	except Exception as error:
		return jsonify(error=str(error), message="error")

	try:
		result = float(calculator.normal(mean, sd, x))
		return jsonify(probability=result, message="success")
	except Exception as error:
		return jsonify(error=str(error), message="error")


@complex_.route("/normal-image")
def normal_graph():
	"""
	used to serve an image to the site
	:return: A graph (.png file)
	"""
	graph_image_path = "static/normal-graph.png"
	return send_file(graph_image_path, mimetype="image/png")


@complex_.route("/complex/binomial", methods=["GET", "POST"])
def binomial():
	"""
	The binomial distribution page
	:return: A template
	"""

	distribution = Distribution("Binomial Distribution", "Discrete Probability Distribution",
	                            "The binomial distribution with parameters n and p is the discrete probability "
	                            "distribution of the number of successes in a sequence of n independent experiments, "
	                            "each asking a yes–no question, and each with its own Boolean-valued outcome: "
	                            "success (with probability p) or failure (with probability q = 1 - p).")
	# Source: https://en.wikipedia.org/wiki/Binomial_distribution
	# probability, mean, variance, standard_deviation = calculator.binomial(n=n, p=p, x=x)
	return render_template("binomial.html",
	                       distribution=distribution, functions=functions)


@complex_.route("/complex/t-distribution", methods=["GET", "POST"])
def t_distribution():
	"""
	The T distribution page
	:return: A template
	"""

	distribution = Distribution("T Distribution", "Continuous Probability Distribution",
	                            "The Student's t-distribution (or simply the t-distribution) is a "
	                            "continuous probability distribution that generalizes the standard normal distribution."
	                            "Like the Normal Distribution, it is symmetric around zero and bell-shaped."
	                            "However, the t-distribution has heavier tails and the amount of probability mass in "
	                            "the tails is controlled by the parameter df (degrees of freedom) . For df = 1 the "
	                            "Student's t distribution becomes the standard Cauchy distribution, whereas "
	                            "for df → ∞ it becomes the standard normal distribution N(0,1)")
	# Source:
	# probability = calculator.t_distribution(x=x, freedom=freedom)
	return render_template("t_distribution.html",
	                       distribution=distribution, functions=functions)


@complex_.route("/complex/f-distribution", methods=["GET", "POST"])
def f_distribution():
	"""
	The F distribution page
	:return: A template
	"""

	distribution = Distribution("F Distribution", "Continuous Probability Distribution",
	                            "The F distribution is a uni-variate continuous distribution often "
	                            "used in hypothesis testing.")
	# Source:  https://www.statlect.com/probability-distributions/F-distribution
	# probability = calculator.f_distribution(x=x, freedom_n=freedom_n, freedom_d=freedom_d)
	return render_template("f_distribution.html",
	                       distribution=distribution, functions=functions)


@complex_.route("/complex/chi-squared-distribution", methods=["GET", "POST"])
def chi_squared():
	"""
	The chi-squared distribution page
	:return: A template
	"""

	distribution = Distribution("Chi Squared Distribution", "Continuous Probability Distribution",
	                            "The chi-squared distribution with k degrees of freedom is the distribution "
	                            "of a sum of the squares of k independent standard normal random variables. The "
	                            "chi-squared distribution is a special case of the gamma distribution and is one of "
	                            "the most widely used probability distributions in inferential statistics, notably in "
	                            "hypothesis testing and in construction of confidence intervals.")
	# Source: https://en.wikipedia.org/wiki/Chi-squared_distribution
	# probability = calculator.chi_squared_distribution(chi_square=chi_square, freedom=freedom)
	return render_template("chi_squared_distribution.html",
	                       distribution=distribution, functions=functions)


@complex_.route("/complex/poisson-distribution", methods=["GET", "POST"])
def poisson_distribution():
	"""
	The poisson distribution page
	:return: A template
	"""

	distribution = Distribution("Poisson Distribution", "Discrete Probability Distribution",
	                            "The Poisson distribution is a discrete probability distribution that "
	                            "expresses the probability of a given number of events occurring in a fixed interval "
	                            "of time or space if these events occur with a known constant mean rate and "
	                            "independently of the time since the last event.")
	# source: https://en.wikipedia.org/wiki/Poisson_distribution
	# probability = calculator.poisson_distribution(k, mean)
	return render_template("poisson-distribution.html", distribution=distribution,
	                       functions=functions)


@complex_.route("/complex/geometric-distribution", methods=["GET", "POST"])
def geometric_distribution():
	"""
	The geometric distribution page
	:return: A template
	"""

	distribution = Distribution("Geometric distribution", "Discrete Probability Distribution",
	                            "The geometric distribution gives the probability that the first occurrence "
	                            "of success requires k independent trials, each with success probability p. "
	                            "If the probability of success on each trial is p, then the probability that the "
	                            "kth trial is the first success is")
	# Source: https://en.wikipedia.org/wiki/Geometric_distribution
	# probability, expected_value, variance, standard_deviation = calculator.geometric_distribution(p, n)
	return render_template("geometric-distribution.html", distribution=distribution, functions=functions)

Stats/main/views.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")

Stats/simple/views.py
import numpy as np
from flask import Blueprint, render_template, jsonify, request, session, flash
import secrets
import pendulum
# moved datetime -> pendulum; because "TypeError: can't subtract offset-naive and offset-aware datetimes" inexplicably

from Stats.simple.utils import Calculator
from Stats import active_tokens

simple = Blueprint("simple", __name__)


@simple.before_request
def before_request():
	if "user_token" not in session:
		session["user_token"] = generate_unique_token()
		session["last_activity"] = pendulum.now()
		active_tokens.add(session["user_token"])

	if pendulum.now() - session["last_activity"] >= pendulum.duration(seconds=7200):
		if session["user_token"] in active_tokens:
			active_tokens.remove(session["user_token"])
			delete_graphs(session["user_token"])
			session.pop("user_token")
			session.pop("last_activity")
			flash("""
			Your session has ended.
			Your graphs have been deleted.
			Reload a page to get a new session
			""", "warning")

	session["last_activity"] = pendulum.now()


def delete_graphs(user_token: str):
	pass


def generate_unique_token() -> str:
	while True:
		token = secrets.token_hex(16)
		if token not in active_tokens:
			return token


@simple.get("/simple")
def home():
	return render_template("simple_home.html")


@simple.post("/simple/calculate")
def calculate():
	# TODO: investigate why values are rounded
	try:
		data = request.json
		values = data.get("dataset", [])
		if len(values) != 0:
			for i in range(len(values)):
				values[i] = int(values[i])

		data_set = np.array(values)

	except Exception as error:
		return jsonify(error=str(error), message="error")

	try:
		calculator = Calculator()
		result = {
			# TODO: verify that these calculations are correct?
			"mean": float(calculator.get_mean(data_set)),
			"range": float(calculator.get_range(data_set)),
			"mode": float(calculator.get_mode(data_set)),
			"median": float(calculator.get_median(data_set)),
			"variance": float(calculator.get_variance(data_set)),
			"standard_deviation": float(calculator.get_standard_deviation(data_set)),
			"mean_deviation": float(calculator.get_mean_deviation(data_set)),
			"lower_quartile": float(calculator.get_lower_quartile(data_set)),
			"upper_quartile": float(calculator.get_upper_quartile(data_set)),
			"inter_quartile": float(calculator.get_inter_quartile_range(data_set)),
			"lower_fence": float(calculator.get_lower_fence(data_set)),
			"upper_fence": float(calculator.get_upper_fence(data_set)),
		}
		return jsonify(result=result, message="success")
	except Exception as error:
		return jsonify(error=str(error), message="error")

Stats/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Theophilus N Nenhanga"/>
    <meta name="description" content="A statistics website"/>
    <title>Statistics Website</title>

    {#<link rel="preload" as="style" onload="this.rel='stylesheet'" id="stylesheet" href="../static/styles.css">#}
    <link rel="stylesheet" id="stylesheet" href="../static/styles.css">

    {% block script %}
        <script src="{{ url_for('static', filename='index.js') }}"></script>
        <script src="{{ url_for('static', filename='simpleStats.js') }}"></script>
        <script src="{{ url_for('static', filename='normalDist.js') }}"></script>
    {% endblock script %}

</head>

<body>
<div class="navigation-shade hide" id="navigation-shade">
    <div class="container">
        <div class="shade-exit">
            <p class="shade-header">Site Navigation</p>
            <button class="shade-link" id="shade-exit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg"
                     viewBox="0 0 16 16">
                    <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"></path>
                </svg>
            </button>
        </div>
    </div>

    <div class="shade-flex container">
        <a href="{{ url_for('main.home') }}" class="shade-link">Home</a>
        <a href="{{ url_for('simple.home') }}" class="shade-link">Simple Stats</a>
        <a href="{{ url_for('complex.home') }}" class="shade-link">Distributions</a>
    </div>
</div>
<div class="container">

    <div class="menu-bar">
        <h1>Statistics Website Clone</h1>
        <button id="shade-button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
            </svg>
        </button>
    </div>

    <div class="navbar">
        <a href="{{ url_for('main.home') }}" class="button home-button">Home</a>
        <div class="nav-buttons">
            <a href="{{ url_for('simple.home') }}" class="button">Simple Stats</a>
            <a href="{{ url_for('complex.home') }}" class="button">Distributions</a>
        </div>
    </div>
</div>

{% with messages = get_flashed_messages() %}
	{% if messages %}
		<ul class="flash-messages">
            {% for message in messages %}
            	<li class="flash-message">{{ message }}</li>
            {% endfor %}
        </ul>
	{% endif %}
{% endwith %}

{% block body %}{% endblock body %}
<div class="container">
    <footer class="footer">
        <div class="footer-info">
            <p>Made by <a href="https://github.com/TheophilusNenhanga" style="text-decoration: underline">Theophilus
                Nenhanga</a></p>
            <p>Thank you for using my site, I hope it helped.</p>
            <p>If you want to see the source code you can check it out on GitHub!</p>
            <a href="https://github.com/TeeEnnEnn/StatisticsWebsiteClone" class="button inner-button-flex"
               target="_blank"> Go to GitHub
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-github"
                     viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            </a>
        </div>
        <div class="footer-right">
            <div class="footer-links">
                <h3>Find your Way around</h3>
                <a href="{{ url_for('simple.home') }}" class="footer-link" style="text-decoration: underline"> Simple
                    Stats</a>
            </div>
            <div class="footer-links">
                <a href="{{ url_for('complex.home') }}" class="footer-link" style="text-decoration: underline">Distributions</a>
                <a href="{{ url_for('complex.normal') }}" class="footer-link">Normal Distribution</a>
                <a href="{{ url_for('complex.poisson_distribution') }}" class="footer-link">Poisson Distribution</a>
                <a href="{{ url_for('complex.geometric_distribution') }}" class="footer-link">Geometric Distribution</a>
                <a href="{{ url_for('complex.binomial') }}" class="footer-link">Binomial Distribution</a>
                <a href="{{ url_for('complex.t_distribution') }}" class="footer-link">T Distribution</a>
                <a href="{{ url_for('complex.f_distribution') }}" class="footer-link">F Distribution</a>
                <a href="{{ url_for('complex.chi_squared') }}" class="footer-link">Chi-Squared Distribution</a>
            </div>

        </div>
        <div class="settings">
            <div class="night-settings">
                <p id="night-mode-prompt">Change to Night Mode</p>
                <button id="night-mode" type="button" class="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         class="bi bi-moon-stars-fill" viewBox="0 0 16 16">
                        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
                        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
                    </svg>
                </button>
            </div>
        </div>

    </footer>
</div>

</body>

</html>

Stats/templates/binomial.html
{% extends "distribution_template.html" %}
{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.binomial') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}

            <div class="form-pair">
                {{ form.n.label(class="form-label") }}
                {{ form.n(class="form-input") }}
                {% for error in form.n.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.p.label(class="form-label") }}
                {{ form.p(class="form-input") }}
                {% for error in form.p.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.x.label(class="form-label") }}
                {{ form.x(class="form-input") }}
                {% for error in form.x.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
            <p class="center">Mean = {{ mean }}</p>
            <p class="center">Variance = {{ variance }}</p>
            <p class="center">Standard Deviation = {{ standard_deviation }}</p>
        </div>
    </div>

{% endblock workspace %}

{% block non_workspace %}
    <div class="explanation">
        <h2 class="explanation-header">Get to know the Distribution</h2>
        <div class="distribution-explanation">

            <div class="left-flex">
                <p>{{ distribution.name }}</p>
                <p>{{ distribution.description }}</p>
            </div>

            <div class="right-flex">
                <p>{{ distribution.explanation }}</p>
            </div>
        </div>


    </div>
{% endblock non_workspace %}

Stats/templates/chi_squared_distribution.html
{% extends "distribution_template.html" %}
{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.chi_squared') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}

            <div class="form-pair">
                {{ form.chi_square.label(class="form-label") }}
                {{ form.chi_square(class="form-input") }}
                {% for error in form.chi_square.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.freedom.label(class="form-label") }}
                {{ form.freedom(class="form-input") }}
                {% for error in form.freedom.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
        </div>
    </div>

{% endblock workspace %}

Stats/templates/complex_home.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <h1 class="page-header">Choose A function</h1>
    </div>

    <div class="container">
        <div class="complex-flex">
            <div class="function-sidebar">
                {% for function in functions %}
                    <a href="/complex/{{ function }}" class="function-text-link">{{ function }}</a>
                {% endfor %}
            </div>
            <div class="function-grid">
                {% for function in functions %}
                    {% if not function == "More To Come!" %}
                        <a href="/complex/{{ function }}" class="button center">{{ function }}</a>
                    {% else %}
                        <a href="" class="button">{{ function }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

Stats/templates/distribution_template.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <h1 class="page-header">{{ distribution.name }}</h1>
    </div>

    <div class="container">
        <div class="complex-flex">
            <div class="function-sidebar">
                {% for function in functions %}
                    {% if not function == "More To Come!" %}
                        <a href="/complex/{{ function }}" class="function-text-link">{{ function }}</a>
                    {% else %}
                        <a href="" class="function-text-link">{{ function }}</a>
                    {% endif %}
                {% endfor %}
            </div>
            {% block workspace %}{% endblock %}
        </div>


        <div class="explanation">
            <h2 class="explanation-header">Get to know the Distribution</h2>
            <div class="distribution-explanation">

                <div class="left-flex">
                    <p>{{ distribution.name }}</p>
                    <p>{{ distribution.description }}</p>
                </div>

                <div class="right-flex">
                    <p>{{ distribution.explanation }}</p>
                </div>
            </div>


        </div>

    </div>
{% endblock body %}

Stats/templates/f_distribution.html
{% extends "distribution_template.html" %}
{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.f_distribution') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}

            <div class="form-pair">
                {{ form.x.label(class="form-label") }}
                {{ form.x(class="form-input") }}
                {% for error in form.x.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.freedom_n.label(class="form-label") }}
                {{ form.freedom_n(class="form-input") }}
                {% for error in form.freedom_n.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.freedom_d.label(class="form-label") }}
                {{ form.freedom_d(class="form-input") }}
                {% for error in form.freedom_d.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
        </div>
    </div>

{% endblock workspace %}

Stats/templates/geometric-distribution.html
{% extends "distribution_template.html" %}
{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.geometric_distribution') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}

            <div class="form-pair">
                {{ form.n.label(class="form-label") }}
                {{ form.n(class="form-input") }}
                {% for error in form.n.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.p.label(class="form-label") }}
                {{ form.p(class="form-input") }}
                {% for error in form.p.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
            <p class="center">Expected value = {{ expected_value }}</p>
            <p class="center">Variance = {{ variance }}</p>
            <p class="center">Standard Deviation = {{ standard_deviation }}</p>
            <p class="center">Standard Deviation = {{ standard_deviation }}</p>
        </div>
    </div>

{% endblock workspace %}

Stats/templates/home.html
{% extends "base.html" %}

{% block body %}
    <div class="container">
        <h1 class="page-header">Statistics Main Page</h1>


        <div class="home-grid">
            <div class="home-tab">
                <h2 class="center">Simple Statistics</h2>
                <p class="center">Capabilities</p>
                <div class="outer-centre-flex">
                    <ol class="capability-list">
                        <li>Descriptive Statistics (eg. mean, variance, median)</li>
                        <li>Graphical Representations</li>
                    </ol>
                </div>

                <div class="center-grid">
                    <a href="/simple" class="button">Simple Stats</a>
                </div>
            </div>

            <div class="home-tab">
                <h2 class="center">Distributions</h2>
                <p class="center">Capabilities</p>
                <div class="outer-centre-flex">
                    <ol class="capability-list">
                        <li>Discrete Distributions</li>
                        <li>Continuous Distributions</li>
                        <li>Graphical Representations</li>
                    </ol>
                </div>
                <div class="center-grid">
                    <a href="/complex" class="button">Distributions</a>
                </div>
            </div>
        </div>
    </div>


{% endblock body %}

Stats/templates/normal.html
{% extends "distribution_template.html" %}

{% block workspace %}
    <div class="distribution-workspace">
        <form action="" method="post" class="distribution-form" id="normal-distribution">
            <div class="form-pair">
                <label for="mean">Mean</label>
                <input type="number" id="mean" step="0.001" placeholder="0" name="mean">
            </div>

            <div class="form-pair">
                <label for="sd">Standard Deviation</label>
                <input type="number" step="0.001" placeholder="1" id="sd" name="sd">
            </div>

            <div class="form-pair">
                <label for="x">x</label>
                <input type="number" step="0.001" placeholder="1.96" id="x" name="x">
            </div>


            <input type="submit" value="Calculate" class="button">
        </form>
        <div class="distribution-results">
            <p class="center" id="probability">Probability = </p>
        </div>
    </div>

{% endblock workspace %}

{% block non_workspace %}
    {% if graph %}
        <div class="complex-graph-grid">
            <h2>{{ distribution_name }} Graph</h2>
            <img src="{{ url_for('complex.normal_graph') }}" alt="A bell shaped curve" class="graph">
        </div>
    {% else %}
        <div class="complex-graph-grid">
            <p>Enter Values to see a graph</p>
        </div>
    {% endif %}
{% endblock non_workspace %}

{#{% block script %}#}
{#    <script>#}
{#        document.addEventListener("DOMContentLoaded", function (){#}
{#           console.log("this works")#}
{#        });#}
{#    </script>#}
{#{% endblock script %}#}

Stats/templates/poisson-distribution.html
{% extends "distribution_template.html" %}
{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.poisson_distribution') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}

            <div class="form-pair">
                {{ form.k.label(class="form-label") }}
                {{ form.k(class="form-input") }}
                {% for error in form.k.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-pair">
                {{ form.mean.label(class="form-label") }}
                {{ form.mean(class="form-input") }}
                {% for error in form.mean.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>
            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
        </div>
    </div>

{% endblock workspace %}

Stats/templates/t_distribution.html
{% extends "distribution_template.html" %}

{% block workspace %}
    <div class="distribution-workspace">
        <form action="{{ url_for('complex.t_distribution') }}" method="post" class="distribution-form">
            {{ form.csrf_token }}
            <div class="form-pair">
                {{ form.x.label(class="form-label") }}
                {{ form.x(class="form-input") }}

                {% for error in form.x.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="form-pair">
                {{ form.freedom.label(class="form-label") }}
                {{ form.freedom(class="form-input") }}

                {% for error in form.freedom.errors %}
                    <span class="error">{{ error }}</span>
                {% endfor %}
            </div>

            {{ form.submit(class="button") }}
        </form>
        <div class="distribution-results">
            <p class="center">Probability = {{ probability }}</p>
        </div>
    </div>

{% endblock workspace %}